/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LastHour: typeof import('./src/components/LastHour.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SteamProfile: typeof import('./src/components/SteamProfile.vue')['default']
    SteamProfile2: typeof import('./src/components/SteamProfile2.vue')['default']
  }
}
